import { describe, expect, it, beforeEach } from 'vitest';
import prisma from '../../database/client';
import { CollaborationService } from '../collaborationService';
import { AuthService } from '../authService';
import { TaskPriority, TaskStatus, Role } from '../../prisma/client';

const BASE_URL = 'http://127.0.0.1:4000';
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

describe('Event Refactoring & Permission Matrix integration tests', () => {
  beforeEach(async () => {
    await prisma.taskHistory.deleteMany({});
    await prisma.taskComment.deleteMany({});
    await prisma.taskAttachment.deleteMany({});
    await prisma.todo.deleteMany({});
    await prisma.teamInvite.deleteMany({});
    await prisma.teamMember.deleteMany({});
    await prisma.team.deleteMany({});
    await prisma.notification.deleteMany({});
    await prisma.activityLog.deleteMany({});
    await prisma.user.deleteMany({});
  });

  it('guarantees minor saves generate zero activity timeline entries and notifications', async () => {
    // 1. Setup Owner & Team task
    const owner = await AuthService.register('owner@example.com', 'password123', 'Owner');
    const team = await CollaborationService.createTeam(owner.id, 'Engineering');
    if (!team) throw new Error('Team creation failed');

    await CollaborationService.createTodo(owner.id, {
      title: 'Initial Title',
      description: 'Initial Description',
      teamId: team.id,
    });

    // Wait for creation events to settle
    await sleep(50);

    // Clear notifications and activity logs generated by creation
    await prisma.notification.deleteMany({});
    await prisma.activityLog.deleteMany({});

    // 2. Perform minor edits (title, description, priority, due date)
    const activeTasks = await prisma.todo.findMany({ where: { teamId: team.id } });
    const taskId = activeTasks[0].id;

    await CollaborationService.updateTodo(owner.id, taskId, {
      title: 'Edited Title',
      description: 'Edited Description',
      priority: TaskPriority.HIGH,
      dueDate: new Date('2026-09-01'),
    });

    // Wait for any events to settle (though none should be dispatched for minor edits)
    await sleep(50);

    // Assert: zero new activity logs and zero new notifications
    const activityLogs = await prisma.activityLog.findMany({});
    const notifications = await prisma.notification.findMany({});

    expect(activityLogs.length).toBe(0);
    expect(notifications.length).toBe(0);

    // But audit log history must exist
    const taskDetails = await CollaborationService.getTodoById(owner.id, taskId);
    const actions = taskDetails.histories.map((h) => h.action);
    expect(actions).toContain('PRIORITY_CHANGED');
    expect(actions).toContain('DUE_DATE_CHANGED');
  });

  it('verifies that task assignment triggers exactly one activity event and one notification', async () => {
    const owner = await AuthService.register('owner2@example.com', 'password123', 'Owner');
    const member = await AuthService.register('member2@example.com', 'password123', 'Member');
    const team = await CollaborationService.createTeam(owner.id, 'Engineering');
    if (!team) throw new Error('Team creation failed');

    const invite = await CollaborationService.inviteMember(owner.id, team.id, member.email);
    await CollaborationService.acceptInvitation(member.id, invite.token);

    const task = await CollaborationService.createTodo(owner.id, {
      title: 'Task for assignment',
      teamId: team.id,
    });

    // Wait for invite and creation events to settle
    await sleep(50);

    // Clear event counters
    await prisma.notification.deleteMany({});
    await prisma.activityLog.deleteMany({});

    // Assign task
    await CollaborationService.updateTodo(owner.id, task.id, {
      assignedToUserId: member.id,
    });

    // Wait for assignment events to settle
    await sleep(50);

    // Assert: exactly one notification sent to Assignee
    const notifications = await prisma.notification.findMany({ where: { userId: member.id } });
    expect(notifications.length).toBe(1);
    expect(notifications[0].type).toBe('TASK_ASSIGNED');

    // Assert: exactly one TASK_ASSIGNED timeline activity entry
    const activityLogs = await prisma.activityLog.findMany({ where: { action: 'TASK_ASSIGNED' } });
    expect(activityLogs.length).toBe(1);
  });

  it('enforces attachment upload and download permissions matrix', async () => {
    const owner = await AuthService.register('owner3@example.com', 'password123', 'Owner');
    const member = await AuthService.register('member3@example.com', 'password123', 'Member');
    const outsider = await AuthService.register('outsider3@example.com', 'password123', 'Outsider');
    const team = await CollaborationService.createTeam(owner.id, 'Engineering');
    if (!team) throw new Error('Team creation failed');

    const invite = await CollaborationService.inviteMember(owner.id, team.id, member.email);
    await CollaborationService.acceptInvitation(member.id, invite.token);

    const task = await CollaborationService.createTodo(owner.id, {
      title: 'Task for attachment checks',
      teamId: team.id,
    });

    // Wait for setup events to settle
    await sleep(50);

    // 1. Regular Member (unassigned) attempts to upload -> Forbidden (403)
    await expect(
      CollaborationService.addAttachment(member.id, task.id, {
        fileName: 'spec.pdf',
        fileType: 'application/pdf',
        fileSize: 1024,
        storagePath: '/uploads/spec.pdf',
      })
    ).rejects.toThrow('Only the assigned member or admins can upload attachments');

    // 2. Assign the task to the member
    await CollaborationService.updateTodo(owner.id, task.id, {
      assignedToUserId: member.id,
    });

    // Wait for assignment events to settle
    await sleep(50);

    // 3. Assigned Member uploads -> Allowed
    const attachment = await CollaborationService.addAttachment(member.id, task.id, {
      fileName: 'spec.pdf',
      fileType: 'application/pdf',
      fileSize: 1024,
      storagePath: '/uploads/spec.pdf',
    });
    expect(attachment.id).toBeDefined();

    // Wait for upload events to settle
    await sleep(50);

    // 4. Download: Owner and Assigned Member are authorized -> Allowed
    // Let's test HTTP download endpoint using fetch
    const ownerRes = await fetch(`${BASE_URL}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: 'owner3@example.com', password: 'password123' }),
    });
    const ownerToken = ((await ownerRes.json()) as any).token;

    const memberRes = await fetch(`${BASE_URL}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: 'member3@example.com', password: 'password123' }),
    });
    const memberToken = ((await memberRes.json()) as any).token;

    const outsiderRes = await fetch(`${BASE_URL}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: 'outsider3@example.com', password: 'password123' }),
    });
    const outsiderToken = ((await outsiderRes.json()) as any).token;

    // Owner download -> Success (200)
    const ownerDlRes = await fetch(`${BASE_URL}/api/attachments/${attachment.id}/download`, {
      headers: { Authorization: `Bearer ${ownerToken}` },
    });
    expect(ownerDlRes.status).toBe(200);
    expect(ownerDlRes.headers.get('content-type')).toBe('application/pdf');

    // Assigned Member download -> Success (200)
    const memberDlRes = await fetch(`${BASE_URL}/api/attachments/${attachment.id}/download`, {
      headers: { Authorization: `Bearer ${memberToken}` },
    });
    expect(memberDlRes.status).toBe(200);

    // Outsider download -> Forbidden (403)
    const outsiderDlRes = await fetch(`${BASE_URL}/api/attachments/${attachment.id}/download`, {
      headers: { Authorization: `Bearer ${outsiderToken}` },
    });
    expect(outsiderDlRes.status).toBe(403);
  });
});
